version: '3.9'

services:
  php-laravel:
    #custom image:
    #como vou precisar de coisas específicas nessa imagem (como o composer por exemplo) vou então criar uma imagem personalizada. Essa imagem será 'buildada' através do Dockerfile
    build: #nesse parâmetro build eu estou especificando onde ele vai 'buildar' a imagem, ou seja, onde se econtra o arquivo Dockerfile...
      #para que não ocorra problemas de permissão no meu Laravel - após os containers estiverem executando - vou então criar um usuário. Para isso vou criar alguns argumentos que serão utilizados na criação desse meu container!
      args:
        user: danidev #aqui eu estou definindo qual o user que irá "rodar os comandos dentro do container"
        uid: 1000 #não sei o que exatamente é isso.... porém parece ser um número aleatório para não conflitar com outros users que já existam no container! acredito que posso escolher qualquer número aqui na real...
      context: ./docker/php #e para isso - para 'buildar'/criar minha imagem - eu defino no contexto (caminho) onde meu arquivo Dockerfile está...
      dockerfile: Dockerfile #aqui eu defino qual o nome do arquivo.... por padrão o nome do arquivo é de fato Dockerfile... porém poderia ser outro tipo "nginx.dockerfile" por exemplo!    
    #nesse caso vou colocar o nome dessa imagem em específica com o nome do meu user do docker.hub!
    image: devdanib/app-laravel-php
    working_dir: /var/www
    container_name: php-laravel
    #tenho que criar o arquivo app/ senão a instalação do Laravel via composer do container não deixa....
    volumes:
      - ./app:/var/www/
    restart: always
    networks:
      - docker-laravel
  
  #nginx
  nginx-laravel:
    image: nginx:alpine
    restart: always
    container_name: nginx-laravel
    ports:
      - 80:80
    volumes:
      - ./app:/var/www
      - ./docker/nginx/:/etc/nginx/conf.d/
    networks:
      - docker-laravel

  #redis
  redis-laravel:
    image: redis:latest
    container_name: redis-laravel
    networks:
      - docker-laravel

  #mysql - Banco de Dados
  mysql-laravel:
    image: mysql:5.7.16
    container_name: mysql-laravel
    environment:
      #essas aqui são as minha variáveis de ambiente para realizar a crição do BD quando subir o container.
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel-app
      MYSQL_USER: usuario
      MYSQL_PASSWORD: senha
    ports:
      # - 3307:3306
      - 127.0.0.1:3307:3306
    expose:
      - 3307
    volumes:
      - ./.data/mysql:/var/lib/mysql
    restart: always
    networks:
      - docker-laravel


networks:
  docker-laravel:
    # driver: bridge